spring.application.name=chattApp
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=Qwen@1204
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA関連（オプション）
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# スタックトレースをレスポンスから除外
server.error.include-stacktrace=never
